version: '3.6'

networks:
  rabbitmq-example:
    driver: bridge

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    networks:
      - rabbitmq-example
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "8081:15672"
      # - "5000:5673" # Expose this port while running the producer and consumer services locally
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5
  provider:
    build: ./provider
    networks:
      - rabbitmq-example
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      RMQ_URL: "amqp://guest:guest@rabbitmq:5673/"
  gateway:
    build: ./gateway
    networks:
      - rabbitmq-example
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      RMQ_URL: "amqp://guest:guest@rabbitmq:5673/"